-- Mise à jour 2026-10-06 : noms en arabe (clubs + joueurs)
-- Import : phpMyAdmin > csc_db > Importer > ce fichier
USE `csc_db`;
ALTER TABLE `classement` ADD COLUMN IF NOT EXISTS `club_ar` VARCHAR(60) DEFAULT NULL AFTER `club`;
ALTER TABLE `joueurs` ADD COLUMN IF NOT EXISTS `nom_ar` VARCHAR(150) DEFAULT NULL AFTER `prenom`;
UPDATE `classement` SET `club_ar`='إ.الجزائر' WHERE `club`='USMA';
UPDATE `classement` SET `club_ar`='ش.بلوزداد' WHERE `club`='CRB';
UPDATE `classement` SET `club_ar`='م.وهران' WHERE `club`='MCO';
UPDATE `classement` SET `club_ar`='ن.بن عكنون' WHERE `club`='ESBA';
UPDATE `classement` SET `club_ar`='ش.قسنطينة' WHERE `club`='CSC';
UPDATE `classement` SET `club_ar`='ش.تموشنت' WHERE `club`='CRT';
UPDATE `classement` SET `club_ar`='م.الجزائر' WHERE `club`='MCA';
UPDATE `classement` SET `club_ar`='ش.القبائل' WHERE `club`='JSK';
UPDATE `classement` SET `club_ar`='م.الرويسات' WHERE `club`='MBR';
UPDATE `classement` SET `club_ar`='أ.أقبو' WHERE `club`='OA';
UPDATE `classement` SET `club_ar`='و.سطيف' WHERE `club`='ESS';
UPDATE `classement` SET `club_ar`='ش.الأبيار' WHERE `club`='JSEB';
UPDATE `classement` SET `club_ar`='إ.خنشلة' WHERE `club`='USMK';
UPDATE `classement` SET `club_ar`='إ.بسكرة' WHERE `club`='USB';
UPDATE `classement` SET `club_ar`='ج.الشلف' WHERE `club`='ASO';
UPDATE `classement` SET `club_ar`='ش.الساورة' WHERE `club`='JSS';
UPDATE `joueurs` SET `nom_ar`='ملالة أسامة عبد الرحمان' WHERE `dossard`=16 AND `categorie` BETWEEN 1 AND 4;
UPDATE `joueurs` SET `nom_ar`='بوحلفاية زكرياء' WHERE `dossard`=1 AND `categorie` BETWEEN 1 AND 4;
UPDATE `joueurs` SET `nom_ar`='نصير عبد المالك' WHERE `dossard`=30 AND `categorie` BETWEEN 1 AND 4;
UPDATE `joueurs` SET `nom_ar`='أتيبو راجابو جونسون' WHERE `dossard`=6 AND `categorie` BETWEEN 1 AND 4;
UPDATE `joueurs` SET `nom_ar`='طوراش روجرز أوشاكي' WHERE `dossard`=24 AND `categorie` BETWEEN 1 AND 4;
UPDATE `joueurs` SET `nom_ar`='زغاد ياسين' WHERE `dossard`=5 AND `categorie` BETWEEN 1 AND 4;
UPDATE `joueurs` SET `nom_ar`='بن الدين مهدي محمد' WHERE `dossard`=21 AND `categorie` BETWEEN 1 AND 4;
UPDATE `joueurs` SET `nom_ar`='بلقوراي محمد فايز' WHERE `dossard`=2 AND `categorie` BETWEEN 1 AND 4;
UPDATE `joueurs` SET `nom_ar`='بن موسى رحماني عماد الدين' WHERE `dossard`=13 AND `categorie` BETWEEN 1 AND 4;
UPDATE `joueurs` SET `nom_ar`='مداحي أسامة' WHERE `dossard`=12 AND `categorie` BETWEEN 1 AND 4;
UPDATE `joueurs` SET `nom_ar`='شيخي عبد المومن' WHERE `dossard`=27 AND `categorie` BETWEEN 1 AND 4;
UPDATE `joueurs` SET `nom_ar`='أيت عبد السلام أحمد' WHERE `dossard`=4 AND `categorie` BETWEEN 1 AND 4;
UPDATE `joueurs` SET `nom_ar`='عيون منذر نور الإسلام' WHERE `dossard`=3 AND `categorie` BETWEEN 1 AND 4;
UPDATE `joueurs` SET `nom_ar`='ديب إبراهيم' WHERE `dossard`=10 AND `categorie` BETWEEN 1 AND 4;
UPDATE `joueurs` SET `nom_ar`='شكال عفاري حاجي' WHERE `dossard`=8 AND `categorie` BETWEEN 1 AND 4;
UPDATE `joueurs` SET `nom_ar`='بيزيمانا جيهاد' WHERE `dossard`=14 AND `categorie` BETWEEN 1 AND 4;
UPDATE `joueurs` SET `nom_ar`='ربيعي ميلود' WHERE `dossard`=25 AND `categorie` BETWEEN 1 AND 4;
UPDATE `joueurs` SET `nom_ar`='بركان مصطفى' WHERE `dossard`=15 AND `categorie` BETWEEN 1 AND 4;
UPDATE `joueurs` SET `nom_ar`='بوزكري ولاء منذر' WHERE `dossard`=7 AND `categorie` BETWEEN 1 AND 4;
UPDATE `joueurs` SET `nom_ar`='بوعصيدة لؤي عبد المنتقم' WHERE `dossard`=22 AND `categorie` BETWEEN 1 AND 4;
UPDATE `joueurs` SET `nom_ar`='بكير محمد إسلام' WHERE `dossard`=11 AND `categorie` BETWEEN 1 AND 4;
UPDATE `joueurs` SET `nom_ar`='شعبان كريم محمت' WHERE `dossard`=18 AND `categorie` BETWEEN 1 AND 4;
UPDATE `joueurs` SET `nom_ar`='جاوشي حميد' WHERE `dossard`=19 AND `categorie` BETWEEN 1 AND 4;
UPDATE `joueurs` SET `nom_ar`='أناتوف مسلم' WHERE `dossard`=20 AND `categorie` BETWEEN 1 AND 4;
UPDATE `joueurs` SET `nom_ar`='الغول نسيم جلول سالم' WHERE `dossard`=26 AND `categorie` BETWEEN 1 AND 4;
UPDATE `joueurs` SET `nom_ar`='أغبانيو ياو مارسيل إيفرا' WHERE `dossard`=9 AND `categorie` BETWEEN 1 AND 4;
UPDATE `joueurs` SET `nom_ar`='لحمري أيمن عبد العزيز' WHERE `dossard`=17 AND `categorie` BETWEEN 1 AND 4;
